- name: clone dotfiles
  become_user: "{{ workstation_user}}"
  git:
    repo: https://github.com/thiagogomesverissimo/dotfiles.git
    dest: "{{ workstation_home }}/.dotfiles"
    update: yes
    force: yes

- name: copy dotfiles
  become_user: "{{ workstation_user}}"
  shell: "cp {{ workstation_home }}/.dotfiles/{{ item }} {{ workstation_home }}/{{ item }}"
  loop:
     - .gitconfig
     - .tmux.conf
     - .vimrc.local
     - .zshrc.local


