- name: Install tmux
  apt:
    name: tmux
    state: latest 
    update_cache: yes

- name: tmuxconf
  become_user: "{{workstation_user}}"
  template: 
    src: templates/tmux.conf
    dest: "{{ workstation_home }}/.tmux.conf"
    mode: 0600

- name: mytmux
  become_user: "{{ workstation_user}}"
  template: 
    src: templates/mytmux.sh
    dest: "{{ workstation_home }}/.mytmux.sh"
    mode: 0600


