- name: Install fdclone
  apt:
    name: fdclone
    state: latest 
    update_cache: yes

- name: clone fzf
  become_user: "{{ workstation_user}}"
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ workstation_home }}/.fzf"
    update: yes

- name: install fzf
  become_user: "{{ workstation_user}}"
  shell: "./install --all"
  args:
    chdir: "{{ workstation_home }}/.fzf"

- name: fonts dir
  file:
    path: "{{ workstation_home }}/.fonts/"
    state: directory

- name: download fonts
  unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Hack.zip"
    dest: "{{ workstation_home }}/.fonts/"
    remote_src: yes

- name: fix owner fonts dir
  file:
    path: "{{ workstation_home }}/.fonts/"
    state: directory
    owner: "{{ workstation_user}}"
    group: "{{ workstation_user}}"


- lineinfile:
    path: "{{ workstation_home }}/.zshrc"
    insertbefore: '^ZSH_THEME'
    line: 'export TERM="xterm-256color"'
