---
- name: desktop provision
  hosts: localhost
  become: yes

  vars:
    virtualbox_apt_package: "virtualbox-6.0"
    vagrant_package_version: '2.2.4'
    rstudio_version: "xenial-1.1.463"

  pre_tasks:

#  - name: disable apport messages
#    lineinfile: >
#      dest=/etc/default/apport
#      line="enabled=0"
#      regexp="enabled="
#      state=present

  - name: update
    apt:
      update_cache: yes

  - name: upgrade
    apt:
      upgrade: dist

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
      autoremove: yes

  - name: Instala pacotes
    apt: name={{ item }} state=installed
    with_items:
      - terminator
      - vim
      - transmission-gtk
      - terminator
      - gtkterm
      - vlc
      - kazam
        #- fritzing
      - gimp
        #- inkscape
      - audacity
        #- r-base
      - thunderbird
        #- nautilus-dropbox
        #- obs-studio

  - name: Instala Spotify
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90 
    apt_repository:
      repo: deb http://repository.spotify.com stable non-free
      state: present
    apt:
      name: spotify-client
      state: present

  roles:
          #- cmprescott.chrome
          #- ferrarimarco.virtualbox
          #- infOpen.vagrant
          #- oefenweb.rstudio
