---
- name: provision
  become: yes
#  hosts: vagrant
  hosts: localhost

  vars:

    # global vars
    workstation_user: thiago
    workstation_home: /home/thiago

    # R
  tasks:

    # dotfiles
    - include_role:
        name: geerlingguy.dotfiles
      become: yes
      become_user: "{{workstation_user}}"
      
      vars:
        dotfiles_home: "{{workstation_home}}"
        dotfiles_repo_local_destination: "{{workstation_home}}/.dotfiles"
        dotfiles_repo: "https://github.com/thiagogomesverissimo/dotfiles.git"
        dotfiles_files:
          - .gitconfig
          - .mytmux.sh
          - .tmux.conf
          - .vimrc.local
