---
- name: provision
  become: yes
#  hosts: vagrant
  hosts: localhost

  vars:

    # global vars
    workstation_user: thiago
    workstation_home: /home/thiago

    # R
  tasks:

    # workstation
    - include_role:
        name: local.workstation
